#!/bin/bash
# Basic Usage Examples for envfix

echo "=== envfix Basic Usage Examples ==="
echo ""

# Example 1: Scan environment
echo "1. Scan your environment for issues"
echo "   Command: envfix scan"
echo ""
echo "   Output shows:"
echo "   - Python, Node.js, Rust, Go installations"
echo "   - Detected virtual environments"
echo "   - Package manager conflicts"
echo "   - Version mismatches"
echo "   - Dependency issues"
echo ""

# Example 2: See detailed output
echo "2. Get JSON output for parsing"
echo "   Command: envfix scan --json"
echo ""
echo "   Useful for:"
echo "   - CI/CD pipelines"
echo "   - Automated processing"
echo "   - Integration with other tools"
echo ""

# Example 3: Get explanation
echo "3. Understand a specific issue"
echo "   Command: envfix explain python_eol"
echo ""
echo "   Returns:"
echo "   - What the issue means"
echo "   - Why it's a problem"
echo "   - How to fix it"
echo "   - Links to more information"
echo ""

# Example 4: Preview repairs
echo "4. Preview changes without applying them"
echo "   Command: envfix repair --dry-run"
echo ""
echo "   Shows what would be changed:"
echo "   - Which dependencies would be installed"
echo "   - Which venvs would be rebuilt"
echo "   - Which files would be modified"
echo ""

# Example 5: Apply repairs
echo "5. Actually fix the issues"
echo "   Command: envfix repair"
echo ""
echo "   Actions taken:"
echo "   - Rebuilds Python virtual environments"
echo "   - Installs/upgrades dependencies"
echo "   - Validates versions"
echo "   - All changes are logged and reversible"
echo ""

# Example 6: Cleanup
echo "6. Remove unused caches and environments"
echo "   Command: envfix clean"
echo ""
echo "   Removes:"
echo "   - Orphaned virtual environments"
echo "   - Pip/npm/cargo cache files"
echo "   - Broken symlinks"
echo "   - Old package installations"
echo ""

# Example 7: Generate manifest
echo "7. Create reproducible environment manifest"
echo "   Command: envfix lock --output env.yaml"
echo ""
echo "   Creates env.yaml with:"
echo "   - All language versions"
echo "   - All dependency versions"
echo "   - Checksums for reproducibility"
echo ""

# Example 8: Full diagnosis
echo "8. Run complete diagnosis and repair"
echo "   Command: envfix doctor"
echo ""
echo "   Combines:"
echo "   - Full scan"
echo "   - Automatic repairs"
echo "   - Cache cleanup"
echo "   - Result report"
echo ""

# Example 9: Initialize config
echo "9. Create project configuration"
echo "   Command: envfix init"
echo ""
echo "   Creates .envfix.yaml with:"
echo "   - Project-specific settings"
echo "   - Minimum version requirements"
echo "   - Exclude patterns"
echo "   - Custom behavior"
echo ""

# Example 10: Common workflow
echo "=== Common Workflow ==="
echo ""
echo "1. Check current state:"
echo "   envfix scan"
echo ""
echo "2. Understand issues:"
echo "   envfix explain <issue_id>"
echo ""
echo "3. Preview fixes:"
echo "   envfix repair --dry-run"
echo ""
echo "4. Apply fixes:"
echo "   envfix repair"
echo ""
echo "5. Cleanup:"
echo "   envfix clean"
echo ""
echo "6. Verify result:"
echo "   envfix scan"
echo ""

echo "=== For More Help ==="
echo "envfix --help              Show all commands"
echo "envfix <command> --help    Show command help"
echo "README.md                  Full documentation"
echo "QUICK_REFERENCE.md         Command reference"
